#!/usr/bin/bash

if [ "$1" == "down" ]; then
  docker compose -f deployments/compose-dev.yml down
else
  go build -o ./target/web cmd/web/main.go
  if [ $? -ne 0 ]; then
    exit 1
  fi

  docker build -t generic-web -f cmd/web/Dockerfile .
  docker compose -f deployments/compose.yml up -d
  # docker exec -it IceMindWeb bash -c "go run cmd/web/main.go"
  docker logs -f IceMindWeb
fi
